export const useActiveUser = () => useState('activeUser', () => '')
export const useAllExercises = () => useState('allExercises', () => [])
export const useWorkouts = () => useState('workouts', () => [])
export const useSelectUpdateWorkout = () => useState('updateWorkout', () => [])
export const useActiveExercise = () => useState('activeExercise', () => '')